### ISSUE TITLE
Крутая игра но

### ISSUE THREAD

**Issue by kakuju** [styrbo/woodman-test#1]
как какать

**Comment by styrbo2** [comment]
какать надо так, как вам удобнее. Важно не терпеть подолгу — это вредно. Вредно также засиживаться на унитазе (или горшке), читать, рыться в телефоне: если какать не хочется — не надо там сидеть, это нефизиологично.
Есть интересные данные, что дефекация в "позе орла" физиологичнее, хотя у большинства из нас стоят унитазы и мы на них чаще просто садимся (это зажимает какую-то там вену, в общем, дуемся мимо цели).
После дефекации/испражнения важно помыть попу, никакая бумага не удалит все частицы кала. В ряде жарких стран и, например, в Финляндии стандартом является установка "гигиенического душа" рядом с унитазом, им удобно подмываться. У нас можно воспользоваться ковшиком или пластиковой бутылкой.

Всё это с большой вероятностью повторит вам ваш колопроктолог, когда он у вас появится :)

**Comment by kakuju** [comment]
большое вам спасибо, теперь я какаю правильно
